import type { Metadata } from 'next';

export const siteConfig: Metadata = {
  title: 'Sprinto',
  description: 'Full-stack Sprinto using Next.js and Supabase.',
  icons: {
    icon: '/icon.svg',
  },
  keywords: [
    'reactjs',
    'nextjs',
    'supabase',
    'supabase-io',
    'next-auth',
    'react-big-calendar',
    'lucide-icons',
    'react-icons',
    'react-day-picker',
    'shadcn-ui',
    'radix-ui',
    'tailwindcss',
    'lodash',
    'react-query',
    'nuqs',
    'sonner',

    'typescript',
    'javascript',
    'vercel',
    'postcss',
    'prettier',
    'eslint',
    'react-dom',
    'html',
    'css',

    'nuqs-state-management',
    'infinite-query',
    'real-time-features',
    'organized-table',
    'filter-table',
    'paginate-table',
    'tasks-management',
    'projects-management',
    'workspaces-management',
    'ui/ux',
    'supabase-db',
    'Sprinto',

    'date-fns',
    'cn',
    'clsx',
    'lucide-react',
  ] as Array<string>,
} as const;
